server:
  port: ${PORT:8080}

spring:
  application:
    name: fortune-ui
  jackson:
    # Omit JSON property if value is null.
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true
