server:
  port: ${PORT:8081}

spring:
  application:
    name: fortune-service
  jackson:
    # Omit JSON property if value is null.
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: '*'
